import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePurchaseOrder = (vendor, scope, projectInfo, quote) => {
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('PURCHASE ORDER', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`PO #: ${Date.now()}`, 15, 35);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 42);
  
  doc.setFont('helvetica', 'bold');
  doc.text('VENDOR:', 15, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(vendor.name, 15, 62);
  doc.text(`Type: ${vendor.type}`, 15, 69);
  doc.text(`Distance: ${vendor.distance} mi`, 15, 76);
  
  doc.setFont('helvetica', 'bold');
  doc.text('PROJECT:', pageWidth - 85, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(projectInfo.name, pageWidth - 85, 62);
  doc.text(projectInfo.loc, pageWidth - 85, 69);
  doc.text(`Project ID: ${projectInfo.id}`, pageWidth - 85, 76);
  
  const tableData = quote.lineItems.map(item => [
    item.name,
    item.id,
    `${item.qty} ${item.unit}`,
    `$${item.unitPrice.toFixed(2)}`,
    `$${item.lineTotal.toFixed(2)}`
  ]);
  
  doc.autoTable({
    startY: 90,
    head: [['Material', 'SKU', 'Quantity', 'Unit Price', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: { 
      fillColor: [30, 64, 175],
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 9
    },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 35 },
      2: { cellWidth: 25 },
      3: { cellWidth: 30, halign: 'right' },
      4: { cellWidth: 30, halign: 'right' }
    }
  });
  
  const finalY = doc.lastAutoTable.finalY + 10;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Subtotal:`, pageWidth - 80, finalY);
  doc.text(`$${quote.subtotal.toFixed(2)}`, pageWidth - 15, finalY, { align: 'right' });
  
  doc.text(`Tax (${(vendor.taxRate * 100).toFixed(1)}%):`, pageWidth - 80, finalY + 7);
  doc.text(`$${quote.tax.toFixed(2)}`, pageWidth - 15, finalY + 7, { align: 'right' });
  
  doc.text(`Delivery Fee:`, pageWidth - 80, finalY + 14);
  doc.text(`$${quote.deliveryFee.toFixed(2)}`, pageWidth - 15, finalY + 14, { align: 'right' });
  
  if (quote.palletFees > 0) {
    doc.text(`Pallet Fees:`, pageWidth - 80, finalY + 21);
    doc.text(`$${quote.palletFees.toFixed(2)}`, pageWidth - 15, finalY + 21, { align: 'right' });
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  const totalY = quote.palletFees > 0 ? finalY + 28 : finalY + 21;
  doc.text(`GRAND TOTAL:`, pageWidth - 80, totalY);
  doc.text(`$${quote.total.toFixed(2)}`, pageWidth - 15, totalY, { align: 'right' });
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by RoofSourcePro', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  return doc;
};

export const downloadPurchaseOrder = (vendor, scope, projectInfo, quote) => {
  const doc = generatePurchaseOrder(vendor, scope, projectInfo, quote);
  const filename = `PO_${vendor.name.replace(/\s/g, '_')}_${Date.now()}.pdf`;
  doc.save(filename);
};

export const getPurchaseOrderBlob = (vendor, scope, projectInfo, quote) => {
  const doc = generatePurchaseOrder(vendor, scope, projectInfo, quote);
  return doc.output('blob');
};
